sharedSecret: c3502bdfacb710a42ac23670bff5048852cc919b
serviceProviders:
  - type: GitHub
    clientId: "123"
    clientSecret: "42"
  - type: Quay
    clientId: "456"
    clientSecret: "54"
baseUrl: https://spi-oauth-route-spi-system.apps.cluster-q5r2s.q5r2s.sandbox239.opentlc.com
