kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../default
  - oauth_route.yaml
  - scm_route.yaml
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/default?ref=a372429ead046f145b972afb241038988caa6cbf


images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    # 0.4.3
    newTag: sha-a372429
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    # 0.4.5
    newTag: sha-21b82a4
  - name: quay.io/redhat-appstudio/service-provider-integration-scm-file-retriever-server
    newName:  quay.io/redhat-appstudio/service-provider-integration-scm-file-retriever-server
    # 0.4.3
    newTag: sha-470697e