kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spiaccesstokens-file-retriever-server-sa
rules:
  - verbs:
      - create
      - get
      - update
      - delete
      - list
    apiGroups:
      - appstudio.redhat.com
    resources:
      - spiaccesstokenbindings
      - spiaccesstokens
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spiaccesstokens-for-file-retriever-server-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spiaccesstokens-file-retriever-server-sa
subjects:
  - kind: ServiceAccount
    name: spi-system-file-retriever-server-sa
    namespace: spi-system
