kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../default
  - ../namespace
  - ingress.yaml
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/default?ref=a372429ead046f145b972afb241038988caa6cbf


patches:
  - target:
      kind: Ingress
      name: spi-oauth-ingress
    path: ingress-patch.json

secretGenerator:
  - name: oauth-config
    behavior: replace
    files:
      - config.yaml
#
#images:
#  - name: quay.io/redhat-appstudio/service-provider-integration-operator
#    newName: quay.io/lkrejci/service-provider-integration-operator:svpi-44
#    newTag: no-k8s-auth
